### ISSUE TITLE
HTTP ERROR: 404 Problem accessing /__files/rechercherClients

### ISSUE THREAD

**Issue by sridharmunendramani** [massamany/WireMockCsv#1]
I did a mvn clean install for wiremockcsv and the build is successfull. I can see wiremockcsv-1.1.1-standalone.jar in my target folder. Then launched using the below command in my terminal

java -jar "##MyProjectPath##/WireMockCsv/target/wiremockcsv-1.1.1-standalone.jar"  --port 8181 --root-dir ".\src\test\resources\factures\mock" --verbose

The application is launched successfully. But when I hit the below request in postman I get not found response. Can someone help me what I am missing here.
http://localhost:8181/rechercherClients

Response:
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
        <title>Error 404 </title>
    </head>
    <body>
        <h2>HTTP ERROR: 404</h2>
        <p>Problem accessing /__files/rechercherClients. Reason:

            <pre>    Not Found</pre>
        </p>
        <hr />
        <i>
            <small>Powered by Jetty://</small>
        </i>
    </body>
</html>

and in my terminal i can see this
**Matched response definition:
(no response definition configured)**

When i hit http://localhost:8181/__admin
I get below response
{
    "mappings": [],
    "meta": {
        "total": 0
    }
}
-------------------------
Am i missing something?

**Comment by massamany** [comment]
Hi,

Are you typing the command from the project directory, i.e. "##MyProjectPath##/WireMockCsv" ? If not, it will not work.
You can try with the command 
java -jar "##MyProjectPath##/WireMockCsv/target/wiremockcsv-1.1.1-standalone.jar" --port 8181 --root-dir "##MyProjectPath##/src/test/resources/factures/mock" --verbose
which will work whatever is the current directory.
