### ISSUE TITLE
How to change the default structure of the response

### ISSUE THREAD

**Issue by Hidayath-S** [massamany/WireMockCsv#3]
Hi massamany,

i want to use the WireMockCsv project to mock my service which returns the response as below.
{
   "accountNumber": 1235688755,
   "balance": 1000,
   "custId": "custId1",
   "acctSts": "Active"
}

but in this project we have a default structure for the response with which the stubbed response is returned as below which i cant use it with my another live service. Basically i dont want to return the name of the object as "data" as shown in the below stubbed response. can you please help?

response from wireMockCsv:
{"data": {
   "accountNumber": "1235688755",
   "balance": "1000.0",
   "custId": "custId1",
   "acctSts": "Active"
}}

**Comment by Hidayath-S** [comment]
Also can we use any JSON response file in side the below structure?

 {
  "structure": {
"data": "${WireMockCsv}"
}

**Comment by Hidayath-S** [comment]
This issue is resolved now.

**Comment by mitchierichie** [comment]
Hey @Hidayath-S  how did you resolve this? 😁
